YemekSepeti.WebUI/Areas/Administrator/Controllers/AddressController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YemekSepeti.Model.Entities;
using YemekSepeti.Service.Option;

namespace YemekSepeti.WebUI.Areas.Administrator.Controllers
{
    public class AddressController : Controller
    {
        // GET: Administrator/Address
        AddressService adresservice = new AddressService();
        ProvinceService ilservice = new ProvinceService();
        CountryService ilceservice = new CountryService();
        DistrictService semtservice = new DistrictService();
        RestaurantService rs = new RestaurantService();

        public ActionResult Index()
        {

            return View(adresservice.GetAll());
        }

        public ActionResult Insert()
        {
            ViewBag.ProvinceID = new SelectList(ilservice.GetActive(), "ID", "ProvinceName");
            ViewBag.CountryID = new SelectList(ilceservice.GetActive(), "ID", "CountryName");
            ViewBag.DistrictID = new SelectList(semtservice.GetActive(), "ID", "DistrictName");
            ViewBag.RestaurantID = new SelectList(rs.GetActive(), "ID", "Name");
            return View();
        }
        [HttpPost]
        public ActionResult Insert(Address item)
        {
            ViewBag.ProvinceID = new SelectList(ilservice.GetActive(), "ID", "ProvinceName", item.ProvinceID);
            ViewBag.CountryID = new SelectList(ilceservice.GetActive(), "ID", "CountryName", item.CountryID);
            ViewBag.DistrictID = new SelectList(semtservice.GetActive(), "ID", "DistrictName", item.DistrictID);
            ViewBag.RestaurantID = new SelectList(rs.GetActive(), "ID", "Name",item.RestaurantID);
            if (ModelState.IsValid)
            {
                bool sonuc = adresservice.Add(item);
                if (sonuc)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Mesaj = "Semt Ekleme işlemi Sirasinda bir hata olustu.Lütfen daha sonra tekrar deneyin.";
                }
            }
            else
            {
                ViewBag.Mesaj = "Girmiş oldugunuz bilgiler hatali formattta veya eksiktir.Lütfen girmeye çaliştiğiniz verileri kontrol edin.";
            }
            return View();
        }

        public ActionResult Update(Guid id)
        {
            Address gadres = adresservice.GetbyID(id);
            ViewBag.ProvinceID = new SelectList(ilservice.GetActive(), "ID", "ProvinceName", gadres.ProvinceID);
            ViewBag.CountryID = new SelectList(ilceservice.GetActive(), "ID", "CountryName", gadres.CountryID);
            ViewBag.DistrictID = new SelectList(semtservice.GetActive(), "ID", "DistrictName", gadres.DistrictID);
            ViewBag.RestaurantID = new SelectList(rs.GetActive(), "ID", "Name", gadres.RestaurantID);

            return View(adresservice.GetbyID(id));
        }

        [HttpPost]
        public ActionResult Update(Address item)
        {
            ViewBag.ProvinceID = new SelectList(ilservice.GetActive(), "ID", "ProvinceName", item.ProvinceID);
            ViewBag.CountryID = new SelectList(ilceservice.GetActive(), "ID", "CountryName", item.CountryID);
            ViewBag.DistrictID = new SelectList(semtservice.GetActive(), "ID", "DistrictName", item.DistrictID);
            ViewBag.RestaurantID = new SelectList(rs.GetActive(), "ID", "Name", item.RestaurantID);
            if (ModelState.IsValid)
            {
                bool sonuc = adresservice.Update(item);
                if (sonuc)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Mesaj = "Adres Güncelleme işlemi Sirasinda bir hata olustu.Lütfen daha sonra tekrar deneyin.";
                }
            }
            else
            {
                ViewBag.Mesaj = "Girmiş oldugunuz bilgiler hatali formattta veya eksiktir.Lütfen girmeye çaliştiğiniz verileri kontrol edin.";
            }
            return View();
        }

        public ActionResult Delete(Guid id)
        {
            adresservice.Remove(id);
            return RedirectToAction("Index");
        }

    }
}

YemekSepeti.WebUI/Areas/Administrator/Views/Address/Index.cshtml
@model List<Address>
@{
    ViewBag.Title = "Adres Listesi";
}

<br />

@Html.ActionLink("Adres Ekle", "Insert", "Address", null, new { @class = "btn btn-default" })

<hr />
<table class="table table-hover">
    <thead>
        <tr>
            <th>Acik Adresi</th>
            <th>Restorant Adi</th>
            <th>İl</th>
            <th>ilçe</th>
            <th>Semt</th>
            <th>Durum</th>
            <th>####</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Address item in Model)
        {
            <tr>


                <td>@item.FullAddress</td>
                <td>@(item.RestaurantID!= null ? item.Restaurant.Name : "-")</td>
                <td>@(item.ProvinceID != null ? item.Province.ProvinceName : "-")</td>

                <td>@(item.CountryID != null ? item.Country.CountryName : "-")</td>
                <td>@(item.DistrictID != null ? item.District.DistrictName : "-")</td>
                <td>
                    @if (item.Status != Status.Deleted)
                    {
                        <span style="background-color:#1daa1c; font-weight:bold; color:#ffffff; padding:5px 10px;">@item.Status</span>
                    }
                    else
                    {
                        <span style="background-color:#ff0000; font-weight:bold; color:#ffffff; padding:5px 10px;">@item.Status</span>
                    }
                </td>
                <td>
                    @Html.ActionLink("Güncelle", "Update", "Address", new { id = item.ID, area = "Administrator" }, null) |

                    @Html.ActionLink("Sil", "Delete", "Address", new { id = item.ID, area = "Administrator" }, null)
                </td>
            </tr>
        }
    </tbody>
</table>

YemekSepeti.WebUI/Areas/Administrator/Views/Address/Insert.cshtml
@model Address
@{
    /**/

    ViewBag.Title = "Adres Ekle";
}

@using (Html.BeginForm("Insert", "Address", FormMethod.Post))
{

    <div class="form-group">
        <label for="CountryName">Acik Adres:</label>
        @Html.TextAreaFor(m => m.FullAddress, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Restorant Seciniz:</label>
        @Html.DropDownList("RestaurantID",null, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Il Seciniz:</label>
        @Html.DropDownList("ProvinceID", null, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Ilçe Seciniz:</label>
        @Html.DropDownList("CountryID", null, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Semt Seciniz:</label>
        @Html.DropDownList("DistrictID", null, htmlAttributes: new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-default">Kaydet</button>
}

YemekSepeti.WebUI/Areas/Administrator/Views/Address/Update.cshtml
@model Address
@{
    /**/

    ViewBag.Title = "Adres Güncelle";
}

@using (Html.BeginForm("Update", "Address", FormMethod.Post))
{

    <div class="form-group">
        <label for="CountryName">Acik Adres:</label>
        @Html.TextAreaFor(m => m.FullAddress, new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Restorant Seciniz:</label>
        @Html.DropDownList("RestaurantID", null, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Il Seciniz:</label>
        @Html.DropDownList("ProvinceID", null, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Ilçe Seciniz:</label>
        @Html.DropDownList("CountryID", null, htmlAttributes: new { @class = "form-control" })
    </div>
    <div class="form-group">
        <label for="name">Semt Seciniz:</label>
        @Html.DropDownList("DistrictID", null, htmlAttributes: new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-default">Güncelle</button>
}