YemekSepeti.WebUI/Areas/Administrator/Controllers/AppUserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YemekSepeti.Model.Entities;
using YemekSepeti.Service.Option;

namespace YemekSepeti.WebUI.Areas.Administrator.Controllers
{
    public class AppUserController : Controller
    {
        // GET: Administrator/AppUser
        AppUserService aus = new AppUserService();

        public ActionResult Index()
        {
            return View(aus.GetAll());
        }
        public ActionResult Insert()
        {
           
            return View();
        }
        [HttpPost]
        public ActionResult Insert(AppUser item)
        { 
            if (ModelState.IsValid)
            {
                bool sonuc = aus.Add(item);
                if (sonuc)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Message = "Kullanıcı ekleme işleminde bir hata oluştu";
                }
            }
            else
            {
                ViewBag.Message = "Kullanıcı ekleme işleminde bir hata oluştu";
            }
            return View();
        }

        public ActionResult Update(Guid id)
        {
            return View(aus.GetbyID(id));
        }
        [HttpPost]
        public ActionResult Update(AppUser item)
        {
            AppUser gelen = aus.GetbyID(item.ID);
            gelen.Name = item.Name;
            gelen.SurName = item.SurName;
            gelen.UserName = item.UserName;
            gelen.EmailAddress = item.EmailAddress;
            gelen.Phone = item.Phone;
            gelen.IsAdministrator = item.IsAdministrator;
            
            bool sonuc = aus.Update(gelen);
            if (sonuc)
            {
                ViewBag.Message = "Güncelleme Başarılı";
                return RedirectToAction("Index");
            }
            else
            {
                ViewBag.Message = "Güncelleme Başarısız";

            }
            return View();
        }
        
        public ActionResult Delete(Guid id)
        {
            aus.Remove(id);
            return RedirectToAction("Index");
        }

    }
}

YemekSepeti.WebUI/Controllers/LoginController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YemekSepeti.Model.Entities;
using YemekSepeti.Service.Option;

namespace YemekSepeti.WebUI.Controllers
{
    public class LoginController : Controller
    {
        // GET: Login
        AppUserService aus = new AppUserService();
        public ActionResult Login(AppUser item)
        {
            if(aus.Any(m=>m.Password==item.Password && m.UserName==item.UserName))
            {
                AppUser gelen = aus.GetByDefault(x => x.UserName == item.UserName);
                bool adminmi = gelen.IsAdministrator;
                if(adminmi)
                {
                    Session["LoginUser"] = gelen;
                    return RedirectToAction("Index", "Restaurant", new { area = "Administrator" });
                }
                else
                {
                    Session["LoginUser"] = gelen;
                    ViewBag.UserName = gelen.UserName;
                    return RedirectToAction("Index","Home");
                }
            }
            else
            {
                //Hatali Kullanici Adi ve Şifre
            }
            return View();
        }

        public ActionResult Son()
        {
            Session["LoginUser"] = null;
            Session["sepetim"] = null;
            Session.Abandon();
            return View("/Views/Home/Index.cshtml");
        }

    }
}

YemekSepeti.WebUI/Views/Shared/_Layout.cshtml
@{
    AppUser Kullanici = (AppUser)Session["LoginUser"];

}

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="pizza, delivery food, fast food, sushi, take away, chinese, italian food">
    <meta name="description" content="">
    <meta name="author" content="Ansonika">
    <title>QuickFood - Quality delivery or take away food</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="~/Content/img/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="~/Content/img/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="~/Content/img/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="~/Content/img/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="~/Content/img/apple-touch-icon-144x144-precomposed.png">

    <!-- GOOGLE WEB FONT -->
    <link href="https://fonts.googleapis.com/css?family=Lato:400,700,900,400italic,700italic,300,300italic" rel="stylesheet" type="text/css">

    <!-- BASE CSS -->
    <link href="~/Content/css/base.css" rel="stylesheet">

    <link href="~/Content/css/skins/square/grey.css" rel="stylesheet">
    <link href="~/Content/css/ion.rangeSlider.css" rel="stylesheet">
    <link href="~/Content/css/ion.rangeSlider.skinFlat.css" rel="stylesheet">

    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->

    <style id="__web-inspector-hide-shortcut-style__" type="text/css">
        .__web-inspector-hide-shortcut__, .__web-inspector-hide-shortcut__ *, .__web-inspector-hidebefore-shortcut__::before, .__web-inspector-hideafter-shortcut__::after {
            visibility: hidden !important;
        }
    </style>
</head>
<body style="overflow: visible;" class="">
    <div class="parallax-mirror" style="visibility: visible; z-index: -100; position: fixed; top: 0px; left: 0px; overflow: hidden; transform: translate3d(0px, 0px, 0px); height: 80px; width: 1247px;"></div>



    <div id="preloader" style="display: none;">
        <div class="sk-spinner sk-spinner-wave" id="status" style="display: none;">
            <div class="sk-rect1"></div>
            <div class="sk-rect2"></div>
            <div class="sk-rect3"></div>
            <div class="sk-rect4"></div>
            <div class="sk-rect5"></div>
        </div>
    </div>


    <header class="">
        <div class="container-fluid">
            <div class="row">
                <div class="col--md-4 col-sm-4 col-xs-4">
                    <a href="index.html" id="logo">
                        <img src="~/Content/img/logo.png" width="190" height="23" alt="" data-retina="true" class="hidden-xs">
                        <img src="~/Content/img/logo_mobile.png" width="59" height="23" alt="" data-retina="true" class="hidden-lg hidden-md hidden-sm">
                    </a>
                </div>
                <nav class="col--md-8 col-sm-8 col-xs-8">
                    <div class="main-menu-2">
                        <ul>
                            @if (Kullanici == null)
                            {
                                <li><a href="#0" data-toggle="modal" data-target="#login_2">Login</a></li>
                                <li><a href="#0" data-toggle="modal" data-target="#register">Register</a></li>
                                <li><a href="#0"><span>Kullanici</span></a></li>
                            }
                            else
                            {
                                <li><a href="#0" data-toggle="modal" data-target="#register"><strong>@Kullanici.UserName</strong></a></li>
                                <li><a href="@Url.Action("Son","Login",null)" data-toggle="modal" data-target="#register"><b>Çıkış Yap</b></a></li>
                            }

                        </ul>
                    </div><!-- End main-menu-2 -->
                </nav>
            </div><!-- End row -->
        </div><!-- End container -->
    </header>

    <section class="parallax-window" id="home" data-parallax="scroll" data-natural-width="1400" data-natural-height="550">
        <!-- End subheader -->

    </section>
    <div class="container margin_60">


        <div class="row">


            @RenderBody()

        </div><!-- End row -->


    </div>
    <footer>
        <div class="container">
            <div class="row">
                <div class="col-md-4 col-sm-3">
                    <h3>Secure payments with</h3>
                    <p>
                        <img src="~/Content/img/cards.png" alt="" class="img-responsive">
                    </p>
                </div>
                <div class="col-md-3 col-sm-3">
                    <h3>About</h3>
                    <ul>
                        <li><a href="about.html">About us</a></li>
                        <li><a href="faq.html">Faq</a></li>
                        <li><a href="contacts.html">Contacts</a></li>
                        <li><a href="#0" data-toggle="modal" data-target="#login_2">Login</a></li>
                        <li><a href="#0" data-toggle="modal" data-target="#register">Register</a></li>
                        <li><a href="#0">Terms and conditions</a></li>
                    </ul>
                </div>
                <div class="col-md-3 col-sm-3" id="newsletter">
                    <h3>Newsletter</h3>
                    <p>
                        Join our newsletter to keep be informed about offers and news.
                    </p>
                    <div id="message-newsletter_2">
                    </div>
                    <form method="post" action="assets/newsletter.php" name="newsletter_2" id="newsletter_2">
                        <div class="form-group">
                            <input name="email_newsletter_2" id="email_newsletter_2" type="email" value="" placeholder="Your mail" class="form-control">
                        </div>
                        <input type="submit" value="Subscribe" class="btn_1" id="submit-newsletter_2">
                    </form>
                </div>

            </div><!-- End row -->
            <div class="row">
                <div class="col-md-12">
                    <div id="social_footer">
                        <ul>
                            <li><a href="#0"><i class="icon-facebook"></i></a></li>
                            <li><a href="#0"><i class="icon-twitter"></i></a></li>
                            <li><a href="#0"><i class="icon-google"></i></a></li>
                            <li><a href="#0"><i class="icon-instagram"></i></a></li>
                            <li><a href="#0"><i class="icon-pinterest"></i></a></li>
                            <li><a href="#0"><i class="icon-vimeo"></i></a></li>
                            <li><a href="#0"><i class="icon-youtube-play"></i></a></li>
                        </ul>
                        <p>
                            ? Quick Food 2019
                        </p>
                    </div>
                </div>
            </div><!-- End row -->
        </div><!-- End container -->
    </footer>


    <div class="layer"></div>


    <div class="modal fade" id="login_2" tabindex="-1" role="dialog" aria-labelledby="myLogin" aria-hidden="true" style="display: none;">
        <div class="modal-dialog" style="margin-top: 64.5px;">
            <div class="modal-content modal-popup">
                <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
                @*<form action="#" class="popup-form" id="myLogin">*@
                @using (Html.BeginForm("Login", "Login", FormMethod.Post, new { @id = "myLogin", @class = "popup-form" }))
                {
                    <div class="login_icon"><i class="icon_lock_alt"></i></div>
                    @*<input type="text" class="form-control form-white" placeholder="Username">*@
                    @Html.TextBox("UserName", null, new { @class = "form-control form-white", placeholder = "UserName" })
                    @*<input type="text" class="form-control form-white" placeholder="Password">*@
                    @Html.TextBox("Password", null, new { @class = "form-control form-white", placeholder = "Password", @type = "password", @id = "password1" })
                    
                    <button type="submit" class="btn btn-submit">Submit</button>
                }
                @*</form>*@
            </div>
        </div>
    </div>

    <!-- Register modal -->
    <div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="myRegister" aria-hidden="true" style="display: none;">
        <div class="modal-dialog" style="margin-top: 0px;">
            <div class="modal-content modal-popup">
                <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
                @*<form action="#" class="popup-form" id="myRegister">*@
                @using (Html.BeginForm("Insert", "AppUser", new { area = "Administrator" }, FormMethod.Post, new { @class = "popup-form" }))
                {
                    <div class="login_icon"><i class="icon_lock_alt"></i></div>
                    @Html.TextBox("UserName", null, new { @class = "form-control form-white", placeholder = "UserName" })
                    @*<input type="text" class="form-control form-white" placeholder="UserName">*@
                    @Html.TextBox("Name", null, new { @class = "form-control form-white", placeholder = "Name" })
                    @*<input type="text" class="form-control form-white" placeholder="Name">*@
                    @Html.TextBox("SurName", null, new { @class = "form-control form-white", placeholder = "SurName" })
                    @*<input type="text" class="form-control form-white" placeholder="Last Name">*@
                    @Html.TextBox("EmailAddress", null, new { @class = "form-control form-white", placeholder = "Email", @type = "email" })
                    @*<input type="email" class="form-control form-white" placeholder="Email">*@
                    @Html.TextBox("Password", null, new { @class = "form-control form-white", placeholder = "Password", @type = "password", @id = "password1" })
                    @*<input type="text" class="form-control form-white" placeholder="Password" id="password1">*@
                    @Html.TextBox("BirthDate", null, new { @class = "form-control form-white", placeholder = "Password", @type = "date" })
                    @*<input type="date" class="form-control form-white" placeholder="Dogum Tarihi" id="dtarih">*@
                    <div id="pass-info" class="clearfix"></div>
                    <div class="checkbox-holder text-left">
                        <div class="checkbox">
                            <input type="checkbox" value="accept_2" id="check_2" name="check_2">
                            <label for="check_2"><span>I Agree to the <strong>Terms &amp; Conditions</strong></span></label>
                        </div>
                    </div>
                    <button type="submit" class="btn btn-submit">Register</button>
                }
                @*</form>*@
            </div>
        </div>
    </div><!-- End Register modal -->
    <!-- COMMON SCRIPTS -->
    <script src="~/Content/js/jquery-2.2.4.min.js"></script>
    <script src="~/Content/js/common_scripts_min.js"></script>
    <script src="~/Content/js/functions.js"></script>
    <script src="~/Content/assets/validate.js"></script>

    @RenderSection("scripts", required: false)

</body>
</html>