YemekSepeti.WebUI/Areas/Administrator/Controllers/ProvinceController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using YemekSepeti.Model.Entities;
using YemekSepeti.Service.Option;

namespace YemekSepeti.WebUI.Areas.Administrator.Controllers
{
    public class ProvinceController : Controller
    {
        // GET: Administrator/Province
        ProvinceService ilservisi = new ProvinceService();
        public ActionResult Index()
        {
            return View(ilservisi.GetAll());
        }
        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Insert(Province item)
        {
            if (ModelState.IsValid)
            {
                bool sonuc = ilservisi.Add(item);
                if (sonuc)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Mesaj = "İL Ekleme işlemi Sirasinda bir hata olustu.Lütfen daha sonra tekrar deneyin.";
                }
            }
            else
            {
                ViewBag.Mesaj = "Girmiş oldugunuz bilgiler hatali formattta veya eksiktir.Lütfen girmeye çaliştiğiniz verileri kontrol edin.";
            }
            return View();
        }

        public ActionResult Update(Guid id)
        {
            return View(ilservisi.GetbyID(id));
        }

        [HttpPost]
        public ActionResult Update(Province item)
        {
            if (ModelState.IsValid)
            {
                bool sonuc = ilservisi.Update(item);
                if (sonuc)
                {
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.Mesaj = "İl Güncelleme işlemi Sirasinda bir hata olustu.Lütfen daha sonra tekrar deneyin.";
                }
            }
            else
            {
                ViewBag.Mesaj = "Girmiş oldugunuz bilgiler hatali formattta veya eksiktir.Lütfen girmeye çaliştiğiniz verileri kontrol edin.";
            }
            return View();
        }

        public ActionResult Delete(Guid id)
        {
            ilservisi.Remove(id);
            return RedirectToAction("Index");
        }
    }
}

YemekSepeti.WebUI/Areas/Administrator/Views/Province/Index.cshtml
@model List<Province>
@{
    ViewBag.Title = "İl Listesi";
}

<h2>Index</h2>

@Html.ActionLink("İl Ekle", "Insert", "Province", null, new { @class = "btn btn-default" })

<hr />

<table class="table table-hover">
    <thead>
        <tr>
            <th>İl Adi</th>
            <th>Olusturulma Tarihi</th>
            <th>Durum</th>
            <th>####</th>
        </tr>
    </thead>
    <tbody>
        @foreach (Province item in Model)
        {
            <tr>
                <td>@item.ProvinceName</td>
                <td>@item.CreatedDate</td>
                <td>
                    @if (item.Status != Status.Deleted)
                    {
                        <span style="background-color:#1daa1c; font-weight:bold; color:#ffffff; padding:5px 10px;">@item.Status</span>
                    }
                    else
                    {
                        <span style="background-color:#ff0000; font-weight:bold; color:#ffffff; padding:5px 10px;">@item.Status</span>
                    }
                </td>
                <td>
                    @Html.ActionLink("Güncelle", "Update", "Province", new { id = item.ID, area = "Administrator" }, null) |

                    @Html.ActionLink("Sil", "Delete", "Province", new { id = item.ID, area = "Administrator" }, null)
                </td>
            </tr>
        }


    </tbody>

</table>

YemekSepeti.WebUI/Areas/Administrator/Views/Province/Insert.cshtml
@model Province
@{
    ViewBag.Title = "İl Ekleme";
}

<h2>Insert</h2>

@using (Html.BeginForm("Insert", "Province", FormMethod.Post))
{
    <div class="form-group">
        <label for="categoryName">İl Adı:</label>
        @Html.TextBoxFor(m => m.ProvinceName, new { @class = "form-control" })
    </div>
    <button type="submit" class="btn btn-default">Kaydet</button>
}

YemekSepeti.WebUI/Areas/Administrator/Views/Province/Update.cshtml
@model Province

@{
ViewBag.Title = "İl Güncelle";
}

@using (Html.BeginForm("Update", "Province", FormMethod.Post))
{
    @Html.HiddenFor(m => m.ID)
    @Html.HiddenFor(m => m.CreatedDate)
    @Html.HiddenFor(m => m.CreatedIP)
    @Html.HiddenFor(m => m.Status)
    @Html.HiddenFor(m => m.ModifiedDate)
    @Html.HiddenFor(m => m.ModifiedIP)

    <div class="form-group">
        <label for="categoryName">İl Adi:</label>
        @Html.TextBoxFor(m => m.ProvinceName, new { @class = "form-control" })
    </div>

    <button type="submit" class="btn btn-default">Güncelle</button>
}